version: '3'

services: 
  chat:
    build: ./chat
    tty: true
    ports:
      - "8080:8080"
    container_name: chat
    depends_on: 
      - mysql
    networks:
      chat:
        ipv4_address: 172.20.0.2
    volumes:
      - ./chat:/go/src/chat

  mysql:
    build: ./db
    tty: true
    ports: 
      - "3306:3306"
    container_name: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: smoty
      MYSQL_DATABASE: chat
    networks:
      chat:
        ipv4_address: 172.20.0.3
  

networks:
  chat:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16



